version: '3.3'
services:
  # database:
  #   image: mariadb
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Ride4Ever
  #   networks:
  #     - network_database
  #   ports:
  #     - 3306:3306
  ride4ever-service-configuration:
    build: ./ride4ever-service-configuration
    restart: always
    hostname: ride4ever-service-configuration
    networks:
      - network_discovery
      - network_configuration
    ports:
      - 9101:9101
  ride4ever-service-discovery:
    build: ./ride4ever-service-discovery
    restart: always
    hostname: ride4ever-service-discovery
    depends_on:
      - ride4ever-service-configuration
    networks:
      - network_discovery
      - network_configuration
    ports:
      - 8761:8761
  ride4ever-service-apigateway:
    depends_on:
      - ride4ever-service-discovery
    build: ./ride4ever-service-apigateway
    restart: always
    hostname: apigateway
    networks:
      - network_discovery
      - network_configuration
    ports:
      - 9600:9600
  ride4ever-microservice-account:
    depends_on:
      - ride4ever-service-apigateway
    build: ./ride4ever-microservice-account
    restart: always
    hostname: account
    networks:
      - network_discovery
      - network_configuration
    #   - network_database
  ride4ever-microservice-biker:
    depends_on:
      - ride4ever-service-apigateway
    build: ./ride4ever-microservice-biker
    restart: always
    hostname: biker
    networks:
      - network_discovery
      - network_configuration
    #   - network_database
  ride4ever-microservice-broker:
    depends_on:
      - ride4ever-service-apigateway
    build: ./ride4ever-microservice-broker
    restart: always
    hostname: broker
    networks:
      - network_discovery
      - network_configuration
    #   - network_database
  ride4ever-microservice-garage:
    depends_on:
      - ride4ever-service-apigateway
    build: ./ride4ever-microservice-garage
    restart: always
    hostname: garage
    networks:
      - network_discovery
      - network_configuration
    #   - network_database
  ride4ever-microservice-club:
    depends_on:
      - ride4ever-service-apigateway
    build: ./ride4ever-microservice-motorcycleclub
    restart: always
    hostname: club
    networks:
      - network_discovery
      - network_configuration
    #   - network_database
  ride4ever-microservice-reservation:
    depends_on:
      - ride4ever-service-apigateway
    build: ./ride4ever-microservice-reservation
    restart: always
    hostname: reservation
    networks:
      - network_discovery
      - network_configuration
    #   - network_database
  ride4ever-microservice-trip:
    depends_on:
      # - database
      # - ride4ever-service-configuration
      - ride4ever-service-discovery
    build: ./ride4ever-microservice-trip
    restart: always
    hostname: trip
    networks:
      - network_discovery
      - network_configuration
    #   - network_database
  ride4ever-microservice-prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - './ride4ever-prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
  ride4ever-microservice-grafana:
    image: grafana/grafana
    restart: always
    ports:
      - 3000:3000
networks:
  # default:
  #   external:
  #     name: ride4ever-backend_default
  # network_database: {}
  network_discovery: {}
  network_configuration: {}
